# Generated by Django 4.0.4 on 2022-10-29 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0045_smmposter'),
    ]

    operations = [
        migrations.CreateModel(
            name='team_batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('tb_startdate', models.DateField(blank=True, null=True)),
                ('tb_enddate', models.DateField(blank=True, null=True)),
                ('tb_progress', models.IntegerField()),
                ('tb_status', models.CharField(default='0', max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='probation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='promissory',
            options={'get_latest_by': ['status']},
        ),
        migrations.AddField(
            model_name='trainer_task',
            name='correction_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trainer_task',
            name='correction_files',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='trainer_task',
            name='verification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='previousteam',
            name='teamname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.create_team'),
        ),
        migrations.AlterField(
            model_name='probation',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.create_team'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.create_team'),
        ),
    ]
