# Generated by Django 4.0.4 on 2022-11-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0046_team_batch_alter_probation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousteam',
            name='trainee_enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previousteam',
            name='trainee_startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
